# Generated by Django 3.2.9 on 2025-06-04 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0004_auto_20250602_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='questionrequest',
            name='answered_question',
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.category'),
        ),
        migrations.AddField(
            model_name='question',
            name='content',
            field=models.TextField(default='Varsayılan içerik'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='questionrequest',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Soran Kullanıcı'),
        ),
        migrations.AlterField(
            model_name='questionrequest',
            name='question_text',
            field=models.TextField(verbose_name='Soru'),
        ),
    ]
