# Generated by Django 3.2.9 on 2025-06-04 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_question_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='asked_times',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='questionrequest',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.category'),
        ),
    ]
