# Generated by Django 3.2.9 on 2025-06-04 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20250604_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='asked_times',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.category'),
        ),
    ]
